## Q1. What are the benefits of the built-in array package, if any?



>Faster execution. Arrays can be accessed and manipulated more efficiently than lists. This is because arrays are stored in contiguous memory, while lists are stored in a linked list data structure.

>Less memory usage. Arrays can use less memory than lists. This is because arrays do not need to store pointers to the next element in the list.

>Easier to manage. Arrays are easier to manage than lists. This is because arrays have a fixed size, while lists can grow or shrink dynamically.

>Support for a variety of data types. Arrays support a variety of data types, including integers, floats, strings, and complex numbers. This makes them more versatile than lists, which can only store objects.

>Built-in functions. The array package comes with a number of built-in functions that make it easy to manipulate arrays. These functions include append(), insert(), remove(), sort(), and search()

## Q2. What are some of the array package's limitations?



>Fixed size: Arrays have a fixed size, which means that they cannot be resized dynamically. This can be a limitation if you need to store a large amount of data or if you need to add or remove elements from the array frequently.

>Not as versatile as lists: Arrays can only store elements of the same data type, while lists can store elements of any data type. This makes lists more versatile than arrays.

>Not as efficient for certain operations: Arrays are not as efficient for certain operations, such as inserting or removing elements from the middle of the array. This is because arrays need to shift all of the elements after the insertion or removal operation.

>Not as flexible as other data structures: Arrays are not as flexible as other data structures, such as linked lists and trees. This is because arrays are a more rigid data structure.

## Q3. Describe the main differences between the array and numpy packages.



>Performance:   NumPy arrays are much faster than Python lists for numerical operations. This is because NumPy arrays are stored in contiguous memory, while Python lists are stored in a linked list data structure.

>Data types:    NumPy arrays can store elements of any data type, while Python lists can only store elements of object type. This makes NumPy arrays more versatile than Python lists.

>Functionality:    NumPy provides a wider range of mathematical functions for operating on arrays than the array package. This makes NumPy arrays more powerful for scientific 
computing applications.

>Ease of use:     NumPy arrays are more complex than Python lists. This can make them more difficult to learn and use.

## Q4. Explain the distinctions between the empty, ones, and zeros functions.



In [6]:
#empty(): Creates an uninitialized array of the specified shape and dtype. The elements of the array are not initialized to any particular value.
import numpy as np
arr = np.empty((3, 2), dtype=int)
print("empty array\n",arr)


#ones(): Creates an array of the specified shape and dtype, filled with ones.
import numpy as np
arr = np.ones((3, 2), dtype=int)
print("ones array\n",arr)


#zeros(): Creates an array of the specified shape and dtype, filled with zeros.
import numpy as np
arr = np.zeros((3, 2), dtype=int)
print("zeros array\n",arr)


empty array
 [[1 1]
 [1 1]
 [1 1]]
ones array
 [[1 1]
 [1 1]
 [1 1]]
zeros array
 [[0 0]
 [0 0]
 [0 0]]


## Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?



>callable argument in the NumPy fromfunction() function is a function that is used to generate the elements of the new array. The function must take as many arguments as the array has dimensions, and it must return a single value.

In [8]:
import numpy as np

def doubles(x):
  return x * 2

#function to create a new array of integers, filled doubles of the numbers from 1 to 10:
arr = np.fromfunction(doubles, (10,), dtype=int)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


## Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?



>We can add a numpy array with a number of integer or floating point

>all thre elements will be operated by the saem operand

In [9]:
import numpy as n
arr = np.array([[1, 2, 3],
                [3,7,9]])

n = 10
result = arr + n
print(result)

[[11 12 13]
 [13 17 19]]


## Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?



> Yes we can use combined operation-assign operators with numpy arrays

In [10]:
import numpy as n
arr = np.array([[1, 2, 3],
                [3,7,9]])

n = 10
arr+=n
print(arr)

[[11 12 13]
 [13 17 19]]


## Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?



>Yes numpy array contain fixed lenghth strings, that we can set while defining the array

>if the given string is longer than the specified length, then the string will be truncated to the size we defined

In [12]:
import numpy as np

string_array = np.array(['apples', 'banana', 'cherry'], dtype='S6')

string_array[1] = 'watermelon' 
string_array


array([b'apples', b'waterm', b'cherry'], dtype='|S6')

>As you can see , the wtermelon is truncated to waterm . ie the size 6

## Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?


> Arrays should have the same size for the operations like addition or substraction

In [14]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = arr1 + arr2
print(result)

#corrsponding numbers will be added to make the resultand array

[5 7 9]


## Q10. What is the best way to use a Boolean array to mask another array?



In [18]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])

mask = np.array([True, False, True, False, False])

masked_Arr = data[mask]

print(masked_Arr)
#masked array will remain only the elements where the mask array have the True values


[1 3]


## Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.



In [21]:
import pandas
import statistics
import numpy as np
import time

data = [5, 6, 9, 3, 8, 9, 6, 4, 7, 9, 6, 25, 67, 4, 16, 17, 14, 1, 8, 4, 9, 8, 8, 7, 6, 88, 4, 4, 5, 6, 9, 3, 8, 9, 6, 4, 7, 9, 6, 25, 67, 4, 16, 17, 14, 1, 8, 4, 9, 8, 8, 7, 6, 88, 4, 4, 4, 16, 17, 14, 1, 8, 4, 9, 8, 8, 7, 6, 88, 4, 4, 5, 6, 9, 3, 8, 9, 6, 4, 7, 9, 6]
data=data*24
# Define a list to store calculations and execution times
calculation_times = []

# Normal Python calculation
start_time = time.time()
mean = sum(data) / len(data)
variance = sum((x - mean) ** 2 for x in data) / len(data)
std_deviation = variance ** 0.5
end_time = time.time()
calculation_times.append(("Normal Python", end_time - start_time))

# By using statistics module (sample standard deviation)
start_time = time.time()
std_deviation = statistics.stdev(data)
end_time = time.time()
calculation_times.append(("Statistics Module (Sample)", end_time - start_time))

# By using statistics module (population standard deviation)
start_time = time.time()
std_deviation = statistics.pstdev(data)
end_time = time.time()
calculation_times.append(("Statistics Module (Population)", end_time - start_time))

# By using numpy
start_time = time.time()
std_deviation = np.std(data)
end_time = time.time()
calculation_times.append(("Numpy", end_time - start_time))

# Sort the calculations by execution time
sorted_calculation_times = sorted(calculation_times, key=lambda x: x[1])

# Print sorted results
for calc_label, exec_time in sorted_calculation_times:
    print(f"\n\n{calc_label} STANDARD DEVIATION: {std_deviation:.6f}, Execution Time: {exec_time:.6f} seconds")




Numpy STANDARD DEVIATION: 17.958210, Execution Time: 0.000000 seconds


Normal Python STANDARD DEVIATION: 17.958210, Execution Time: 0.001013 seconds


Statistics Module (Sample) STANDARD DEVIATION: 17.958210, Execution Time: 0.003988 seconds


Statistics Module (Population) STANDARD DEVIATION: 17.958210, Execution Time: 0.003998 seconds


>NUMPY STANDARD DEVIATION WAS THE FASTEST TO FIND THE DEVIATION

## 12. What is the dimensionality of a Boolean mask-generated array?

> The dimensionality of a Boolean mask-generated array is the same as the dimensionality of the original array that the mask is applied to. In other words, if you have a 1D array and you apply a Boolean mask to it, the resulting Boolean mask-generated array will also be 1D. If you have a 2D array and apply a Boolean mask, the resulting array will be 2D, and so on.