## Q1. What is the distinction between a numpy array and a pandas data frame? Is there a way to convert between the two if there is?



>Numpy arrays and Pandas DataFrames are both data structures used for handling and manipulating data

>Numpy arrays are designed for homogeneous data, meaning that all elements in a numpy array must have the same data type

>Pandas DataFrames are designed for heterogeneous data, where columns can have different data types. This makes them suitable for tabular data similar to a spreadsheet or SQL table.

> Numpy arrays can be multidimensional, allowing you to work with data in multiple dimensions

>DataFrames represent data in a tabular form, with rows and columns. Each column can have a unique data type, and columns are labeled with names

In [6]:
#converting numpy array into pandas dataframe
import pandas as pd
import numpy as np

numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
print("numpy array \n",numpy_array)
df = pd.DataFrame(numpy_array, columns=["A", "B", "C"])
print("After converting to dataframe\n",df)

#converting pandas dataframe into numpy array
df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
print("\n\n\n Dataframe before converting\n",df)
numpy_array = df.to_numpy()
print("\nDataframe after converting into numpy array\n",numpy_array)


numpy array 
 [[1 2 3]
 [4 5 6]]
After converting to dataframe
    A  B  C
0  1  2  3
1  4  5  6



 Dataframe before converting
    A  B
0  1  4
1  2  5
2  3  6

Dataframe after converting into numpy array
 [[1 4]
 [2 5]
 [3 6]]


## Q2. What can go wrong when an user enters in a stock-ticker symbol, and how do you handle it?



The ticker symbol may not exist. This can happen if the user misspells the ticker symbol or if the company has delisted from the stock exchange

The ticker symbol may be for a different exchange. For example, the user may enter the ticker symbol for Apple Inc. (AAPL) on the New York Stock Exchange (NYSE), but the company is also traded on the Nasdaq Stock Exchange (NASDAQ)

The ticker symbol may be for a closed market. This can happen if the stock exchange is closed for the day or if the market is closed due to a holiday

The ticker symbol may be for a security that is not tradable. This can happen if the security is illiquid or if it is a restricted security

## Q3. Identify some of the plotting techniques that are used to produce a stock-market chart.



>Line chart, A line chart is the simplest type of chart and it shows the closing price of a stock over time. The closing price is the price of a stock at the end of the trading day.

>Candlestick chart, A candlestick chart is a more advanced type of chart that shows the opening, closing, highest, and lowest prices of a stock over time. The candlesticks can be used to identify trends and patterns in the stock market

>Bar chart,  A bar chart is similar to a line chart, but it shows the opening, closing, highest, and lowest prices of a stock as bars. The bars can be used to identify trends and patterns in the stock market

## Q4. Why is it essential to print a legend on a stock market chart?



It makes the chart easier to read: The legend helps the reader to quickly identify the different elements of the chart, such as the different colors, symbols, or lines

It helps to avoid confusion: The legend helps to avoid confusion by ensuring that the reader knows what each element of the chart represents

It improves the readability of the chart: The legend makes the chart more readable by providing a clear and concise explanation of the different element

It is a standard practice: It is a standard practice to print a legend on a stock market chart. This makes it easier for the reader to understand the chart, regardless of the source

## Q5. What is the best way to limit the length of a pandas data frame to less than a year?



In [8]:
import pandas as pd
import datetime as dt


df = pd.DataFrame({
    "Date": pd.to_datetime(["2023-01-01", "2023-02-01", "2023-03-01", "2023-04-01", "2023-05-01", "2023-05-01", "2021-05-01", "2020-05-01"]),
    "Value": [1, 2, 3, 4, 5, 6, 7, 8]
})

#get the curent year
current_date = pd.to_datetime(dt.datetime.now().date())

#get the year for one year ago , which is curreny year -1
one_year_ago = current_date - pd.DateOffset(years=1)

#do the filtering
df_filtered = df[df['Date'] >= one_year_ago]

print(df_filtered)


        Date  Value
0 2023-01-01      1
1 2023-02-01      2
2 2023-03-01      3
3 2023-04-01      4
4 2023-05-01      5
5 2023-05-01      6


## Q6. What is the definition of a 180-day moving average?



>A moving average is a trend-following indicator, which means that it is used to identify the direction of the trend. A rising moving average indicates that the trend is up, while a falling moving average indicates that the trend is down.

>The 180-day moving average can be used as a guide for entering and exiting trades. For example, a trader might buy a security when the price breaks above the 180-day moving average and sell the security when the price falls below the 180-day moving average.

## Q7. Did the chapter's final example use "indirect" importing? If so, how exactly do you do it?

indirect importing has two forms

>import module_name

>import module_name as alias_name